// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type ImageConversion struct {
	ConversionID  int32     `json:"conversion_id"`
	UserID        int32     `json:"user_id"`
	ImageName     string    `json:"image_name"`
	ExtractedText string    `json:"extracted_text"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	UserID         int64     `json:"user_id"`
	UserName       string    `json:"user_name"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
